# Generated by Django 4.0.1 on 2022-01-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogposts',
            new_name='Blogpost',
        ),
    ]
