# Generated by Django 4.0.1 on 2022-01-21 08:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_blogposts_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogpost_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'content', 'author']),
        ),
    ]
