# Generated by Django 4.0.1 on 2022-01-29 20:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_blogpost_blogpost_slug_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
