# Generated by Django 4.0.1 on 2022-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_contact_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='msg',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
